// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-o3amaGVK6yGxLXJ17uPq9CwICr4N8HQ',
    appId: '1:1073945365730:web:051e86325db595661362bb',
    messagingSenderId: '1073945365730',
    projectId: 'authenticguards-8dee8',
    authDomain: 'authenticguards-8dee8.firebaseapp.com',
    storageBucket: 'authenticguards-8dee8.appspot.com',
    measurementId: 'G-50BSLMCYS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjyWYVbBre6tAi7j4DiEqGmE5UOPj_XE',
    appId: '1:1073945365730:android:387b4f13378698691362bb',
    messagingSenderId: '1073945365730',
    projectId: 'authenticguards-8dee8',
    storageBucket: 'authenticguards-8dee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuzO5wFA7dtDBGoJk4ib9FjWDx5E73X8',
    appId: '1:1073945365730:ios:ba4332cb1b6f3ba71362bb',
    messagingSenderId: '1073945365730',
    projectId: 'authenticguards-8dee8',
    storageBucket: 'authenticguards-8dee8.appspot.com',
    androidClientId: '1073945365730-3f4md010fcou8u3rcg9n0ooq8qkh0uh4.apps.googleusercontent.com',
    iosClientId: '1073945365730-48fff1nv3jfh3gj0agr3qmdl3cl4ktsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticGuards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPuzO5wFA7dtDBGoJk4ib9FjWDx5E73X8',
    appId: '1:1073945365730:ios:d4dce7b9db55228d1362bb',
    messagingSenderId: '1073945365730',
    projectId: 'authenticguards-8dee8',
    storageBucket: 'authenticguards-8dee8.appspot.com',
    androidClientId: '1073945365730-3f4md010fcou8u3rcg9n0ooq8qkh0uh4.apps.googleusercontent.com',
    iosClientId: '1073945365730-o3asbum00ukkr08vebsg6ntvpdo8m728.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticGuards.RunnerTests',
  );
}
